add_positionnal_outputs: true
alpha_adjacency: 0.2
alpha_edge_features: 0.1
alpha_edge_labels: 0.2
alpha_h: 1
alpha_marginals: 1
alpha_node_features: 0.1
alpha_node_labels: 1
base_lr: 0.0001
batchsize: 256
dataset: PUBCHEM_32
decay_mode: cosine
decoder_model: evoformer
device: cuda
dropout_attn: 0.0
dropout_mlp: 0.0
dropout_skip: 0.0
edge_features_dim: 1
edge_hidden_dim: null
edge_labels_dim: 6
edge_model_dim: 128
edge_pos_dim: 32
encoder_model: evoformer
epsilon: 0.0001
fixed_n_iters_sinkhorn: true
graph_embedding_dim: 64
graph_embedding_size: 32
hard_matcher: false
last_iter_grad_sinkhorn: false
log_every: 100
logger: mlflow
mask_self_loops: false
max_grad_norm: 0.1
max_iter_sinkhorn: 50
n_eval_interval: 100000
n_grad_steps: 1500000
n_heads: 4
n_layers: 7
n_layers_gnn: 3
n_nodes_max: 32
n_samples_eval: 10000
n_warmup_steps: 16000
n_workers: 8
node_features_dim: 64
node_hidden_dim: 256
node_labels_dim: 32
node_model_dim: 256
node_pos_dim: 16
norm_post_or_pre: pre
normalize_cost_matrix: true
matcher_dim: 64
matcher_model: sinkhorn
run_name: run01
targeter_suffix: default
tol_sinkhorn: 0.01
triangular_attention_mode: none
triangular_multiplication_mode: row
weight_decay: 0